name 'webserver'
maintainer 'Bill ONeill'
maintainer_email 'woneill@pobox.com'
license 'all_rights'
description 'Installs/Configures webserver'
long_description 'Installs/Configures webserver'
version '0.1.0'

depends 'nginx', '~> 2.7.6'
depends 'hhvm',  '~> 0.6.0'
