name 'blog'
maintainer 'Bill ONeill'
maintainer_email 'woneill@pobox.com'
license 'all_rights'
description 'Installs/Configures blog'
long_description 'Installs/Configures blog'
version '0.1.0'

depends 'webserver', '~> 0.1.0'
depends 'wordpress', '~> 3.0.0'
